"""initial schema

Revision ID: aebdac3ccfbc
Revises: 
Create Date: 2026-10-07 09:09:58.241735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'aebdac3ccfbc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector must exist before any vector column (autogenerate does not emit extensions).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sku', sa.String(length=32), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=16), server_default='success', nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_events_agent_ts', 'agent_events', ['agent', 'ts'], unique=False)
    op.create_index('ix_agent_events_ts', 'agent_events', ['ts'], unique=False)
    op.create_table('carriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('on_time_rate', sa.Float(), nullable=False),
    sa.Column('avg_transit_days', sa.Integer(), nullable=False),
    sa.Column('cost_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('ocean','air','road','rail')", name='ck_carriers_mode'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('kb_sources',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('collection', sa.String(length=64), nullable=False),
    sa.Column('source_key', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('chunk_ids', sa.ARRAY(sa.String(length=64)), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('ocr', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('uploaded_by', sa.String(length=120), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("classification IN ('public','internal','restricted')", name='ck_kb_sources_classification'),
    sa.CheckConstraint("status IN ('indexed','processing','failed')", name='ck_kb_sources_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection', 'source_key', name='uq_kb_sources_collection_key')
    )
    op.create_table('kb_state',
    sa.Column('collection', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('collection')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('href', sa.String(length=300), nullable=True),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pack_size', sa.Integer(), server_default='1', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('pack_size > 0', name='ck_products_pack_size'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_products_unit_cost'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('on_time_rate', sa.Float(), nullable=False),
    sa.Column('defect_rate', sa.Float(), nullable=False),
    sa.Column('fill_rate', sa.Float(), nullable=False),
    sa.Column('risk', sa.String(length=16), server_default='low', nullable=False),
    sa.Column('contract_expiry', sa.Date(), nullable=False),
    sa.Column('certifications', sa.ARRAY(sa.String(length=40)), server_default='{}', nullable=False),
    sa.Column('spend_ytd', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk IN ('low','medium','high','critical')", name='ck_suppliers_risk'),
    sa.CheckConstraint('on_time_rate BETWEEN 0 AND 1 AND defect_rate BETWEEN 0 AND 1 AND fill_rate BETWEEN 0 AND 1', name='ck_suppliers_rates'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse', sa.String(length=80), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('allocated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('on_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_age_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('allocated <= on_hand', name='ck_inventory_allocated'),
    sa.CheckConstraint('on_hand >= 0 AND allocated >= 0 AND on_order >= 0', name='ck_inventory_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'warehouse', name='uq_inventory_product_warehouse')
    )
    op.create_table('kb_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('collection', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=24), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('is_parent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=True),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('supplier_id', sa.String(length=16), nullable=True),
    sa.Column('skus', sa.ARRAY(sa.String(length=32)), server_default='{}', nullable=False),
    sa.Column('region', sa.String(length=16), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('ocr', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['kb_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kb_chunks_embedding', 'kb_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_kb_chunks_filters', 'kb_chunks', ['collection', 'classification', 'doc_type'], unique=False)
    op.create_index('ix_kb_chunks_skus', 'kb_chunks', ['skus'], unique=False, postgresql_using='gin')
    op.create_index('ix_kb_chunks_source', 'kb_chunks', ['source_id'], unique=False)
    op.create_index('ix_kb_chunks_tsv', 'kb_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant')", name='ck_messages_role'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('notification_reads',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'notification_id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=24), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','approved','sent','received','cancelled')", name='ck_po_status'),
    sa.CheckConstraint('quantity > 0 AND unit_price > 0', name='ck_po_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_index('ix_po_product', 'purchase_orders', ['product_id'], unique=False)
    op.create_index('ix_po_supplier_status', 'purchase_orders', ['supplier_id', 'status'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_sales_quantity'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'sale_date', name='uq_sales_product_date')
    )
    op.create_index('ix_sales_product_date', 'sales', ['product_id', 'sale_date'], unique=False)
    op.create_table('supplier_products',
    sa.Column('supplier_id', sa.String(length=16), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moq', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('preferred', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('unit_price > 0 AND moq > 0 AND lead_time_days > 0', name='ck_supplier_products_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('supplier_id', 'product_id')
    )
    op.create_index('ix_supplier_products_product', 'supplier_products', ['product_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=32), nullable=False),
    sa.Column('supplier_id', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','approved','rejected','expired')", name='ck_approvals_status'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index('ix_approvals_status', 'approvals', ['status'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.String(length=16), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=80), nullable=False),
    sa.Column('destination', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('promised_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','in_transit','at_customs','delayed','delivered')", name='ck_shipments_status'),
    sa.CheckConstraint('units > 0', name='ck_shipments_units'),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shipments_product', 'shipments', ['product_id'], unique=False)
    op.create_index('ix_shipments_status', 'shipments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shipments_status', table_name='shipments')
    op.drop_index('ix_shipments_product', table_name='shipments')
    op.drop_table('shipments')
    op.drop_index('ix_approvals_status', table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_supplier_products_product', table_name='supplier_products')
    op.drop_table('supplier_products')
    op.drop_index('ix_sales_product_date', table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_po_supplier_status', table_name='purchase_orders')
    op.drop_index('ix_po_product', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_table('notification_reads')
    op.drop_index('ix_messages_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_kb_chunks_tsv', table_name='kb_chunks', postgresql_using='gin')
    op.drop_index('ix_kb_chunks_source', table_name='kb_chunks')
    op.drop_index('ix_kb_chunks_skus', table_name='kb_chunks', postgresql_using='gin')
    op.drop_index('ix_kb_chunks_filters', table_name='kb_chunks')
    op.drop_index('ix_kb_chunks_embedding', table_name='kb_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('kb_chunks')
    op.drop_table('inventory')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_table('notifications')
    op.drop_table('kb_state')
    op.drop_table('kb_sources')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('carriers')
    op.drop_index('ix_agent_events_ts', table_name='agent_events')
    op.drop_index('ix_agent_events_agent_ts', table_name='agent_events')
    op.drop_table('agent_events')
    # ### end Alembic commands ###
